<<<<<<< HEAD
[2024-02-21 13:35:57 +0000] [107514] [INFO] Starting gunicorn 21.2.0
[2024-02-21 13:35:57 +0000] [107514] [INFO] Listening at: http://0.0.0.0:8000 (107514)
[2024-02-21 13:35:57 +0000] [107514] [INFO] Using worker: sync
[2024-02-21 13:35:57 +0000] [107516] [INFO] Booting worker with pid: 107516
[2024-02-21 13:35:57 +0000] [107516] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wsgi'
[2024-02-21 13:35:57 +0000] [107516] [INFO] Worker exiting (pid: 107516)
[2024-02-21 13:35:57 +0000] [107514] [ERROR] Worker (pid:107516) exited with code 3
[2024-02-21 13:35:57 +0000] [107514] [ERROR] Shutting down: Master
[2024-02-21 13:35:57 +0000] [107514] [ERROR] Reason: Worker failed to boot.
[2024-02-21 13:43:41 +0000] [107630] [INFO] Starting gunicorn 21.2.0
[2024-02-21 13:43:41 +0000] [107630] [INFO] Listening at: http://0.0.0.0:8000 (107630)
[2024-02-21 13:43:41 +0000] [107630] [INFO] Using worker: sync
[2024-02-21 13:43:41 +0000] [107632] [INFO] Booting worker with pid: 107632
[2024-02-21 13:43:41 +0000] [107633] [INFO] Booting worker with pid: 107633
[2024-02-21 13:43:41 +0000] [107634] [INFO] Booting worker with pid: 107634
[2024-02-21 13:43:41 +0000] [107635] [INFO] Booting worker with pid: 107635
[2024-02-21 14:05:54 +0000] [107630] [CRITICAL] WORKER TIMEOUT (pid:107634)
[2024-02-21 14:05:54 +0000] [107634] [INFO] Worker exiting (pid: 107634)
Database connection successful
[2024-02-21 14:05:54 +0000] [107630] [ERROR] Worker (pid:107634) exited with code 1
[2024-02-21 14:05:54 +0000] [107630] [ERROR] Worker (pid:107634) exited with code 1.
[2024-02-21 14:05:54 +0000] [107979] [INFO] Booting worker with pid: 107979
[2024-02-21 14:20:05,455] ERROR in app: Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/ubuntu/Tomorrow/web-flask/app.py", line 308, in dashboard
    user = get_user_info(user_id)
  File "/home/ubuntu/Tomorrow/web-flask/app.py", line 282, in get_user_info
    user['events'] = get_user_events(user_id)
TypeError: 'NoneType' object does not support item assignment
[2024-02-21 14:21:09 +0000] [107630] [CRITICAL] WORKER TIMEOUT (pid:107633)
[2024-02-21 14:21:09 +0000] [107633] [INFO] Worker exiting (pid: 107633)
Database connection successful
[2024-02-21 14:21:09 +0000] [107630] [ERROR] Worker (pid:107633) exited with code 1
[2024-02-21 14:21:09 +0000] [107630] [ERROR] Worker (pid:107633) exited with code 1.
[2024-02-21 14:21:09 +0000] [108329] [INFO] Booting worker with pid: 108329
[2024-02-21 14:21:48 +0000] [107630] [CRITICAL] WORKER TIMEOUT (pid:107979)
[2024-02-21 14:21:48 +0000] [107979] [INFO] Worker exiting (pid: 107979)
Database connection successful
Debug: User Info - {'id': 1, 'first_name': 'Michael', 'last_name': 'Machohi', 'username': 'sierra-95', 'email': 'michaelmachohi@gmail.com', 'dob': datetime.date(2002, 10, 3), 'password': '$2b$12$CVF7PYWCBLDVmVjA4Zcxr.udP5C9hMnBYpDw56Rc2IWToa.KZHHeC', 'events': []}
User ID: 1
User ID: 1
1
[2024-02-21 14:21:48 +0000] [107630] [ERROR] Worker (pid:107979) exited with code 1
[2024-02-21 14:21:48 +0000] [107630] [ERROR] Worker (pid:107979) exited with code 1.
[2024-02-21 14:21:48 +0000] [108333] [INFO] Booting worker with pid: 108333
[2024-02-21 14:23:20,590] ERROR in app: Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/ubuntu/Tomorrow/web-flask/app.py", line 308, in dashboard
    user = get_user_info(user_id)
  File "/home/ubuntu/Tomorrow/web-flask/app.py", line 282, in get_user_info
    user['events'] = get_user_events(user_id)
TypeError: 'NoneType' object does not support item assignment
[2024-02-21 18:38:04 +0000] [107630] [CRITICAL] WORKER TIMEOUT (pid:108333)
[2024-02-21 18:38:04 +0000] [108333] [INFO] Worker exiting (pid: 108333)
Database connection successful
Debug: User Info - {'id': 2, 'first_name': 'Coal', 'last_name': 'Art', 'username': 'Coal', 'email': 'coalart64@gmail.com', 'dob': datetime.date(2024, 2, 16), 'password': '$2b$12$P/t8V0P0Ui3O.3IHDYIGBuoqK1YdoLSX/IlIvaxJgYotKydxerj7C', 'events': []}
Debug: User Info - {'id': 2, 'first_name': 'Coal', 'last_name': 'Art', 'username': 'Coal', 'email': 'coalart64@gmail.com', 'dob': datetime.date(2024, 2, 16), 'password': '$2b$12$P/t8V0P0Ui3O.3IHDYIGBuoqK1YdoLSX/IlIvaxJgYotKydxerj7C', 'events': []}
Debug: User Info - {'id': 1, 'first_name': 'Michael', 'last_name': 'Machohi', 'username': 'sierra-95', 'email': 'michaelmachohi@gmail.com', 'dob': datetime.date(2002, 10, 3), 'password': '$2b$12$CVF7PYWCBLDVmVjA4Zcxr.udP5C9hMnBYpDw56Rc2IWToa.KZHHeC', 'events': []}
User ID: 1
1
[2024-02-21 18:38:04 +0000] [107630] [ERROR] Worker (pid:108333) exited with code 1
[2024-02-21 18:38:04 +0000] [107630] [ERROR] Worker (pid:108333) exited with code 1.
[2024-02-21 18:38:04 +0000] [109769] [INFO] Booting worker with pid: 109769
Database connection successful
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://10.247.42.255:8000
Press CTRL+C to quit
127.0.0.1 - - [21/Feb/2024 19:14:41] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [21/Feb/2024 19:14:46] "GET /login_account HTTP/1.0" 200 -
127.0.0.1 - - [21/Feb/2024 19:14:52] "POST /login HTTP/1.0" 302 -
127.0.0.1 - - [21/Feb/2024 19:14:52] "GET /dashboard HTTP/1.0" 200 -
127.0.0.1 - - [21/Feb/2024 19:15:01] "GET /all_future_tasks HTTP/1.0" 200 -
127.0.0.1 - - [21/Feb/2024 19:15:28] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [21/Feb/2024 19:15:37] "GET /welcome_create_account HTTP/1.0" 200 -
127.0.0.1 - - [21/Feb/2024 19:16:20] "GET /create_account_names HTTP/1.0" 200 -
127.0.0.1 - - [21/Feb/2024 19:16:43] "POST /create_account_names HTTP/1.0" 302 -
127.0.0.1 - - [21/Feb/2024 19:16:43] "GET /create_account_dob HTTP/1.0" 200 -
127.0.0.1 - - [21/Feb/2024 19:16:48] "POST /create_account_dob HTTP/1.0" 302 -
127.0.0.1 - - [21/Feb/2024 19:16:49] "GET /create_account_password HTTP/1.0" 200 -
127.0.0.1 - - [21/Feb/2024 19:17:00] "POST /create_account_password HTTP/1.0" 200 -
127.0.0.1 - - [21/Feb/2024 19:17:07] "GET /dashboard HTTP/1.0" 200 -
127.0.0.1 - - [21/Feb/2024 19:21:57] "GET /dashboard HTTP/1.0" 200 -
127.0.0.1 - - [21/Feb/2024 19:32:36] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [21/Feb/2024 19:32:37] "GET /favicon.ico HTTP/1.0" 404 -
127.0.0.1 - - [21/Feb/2024 19:32:38] "GET /favicon.ico HTTP/1.0" 404 -
127.0.0.1 - - [21/Feb/2024 19:37:11] "GET /wp-admin/setup-config.php?step=1 HTTP/1.0" 404 -
127.0.0.1 - - [21/Feb/2024 19:37:11] "GET /wordpress/wp-admin/setup-config.php?step=1 HTTP/1.0" 404 -
127.0.0.1 - - [21/Feb/2024 19:37:12] "GET /old/wp-admin/setup-config.php?step=1 HTTP/1.0" 404 -
=======
[2024-02-21 18:32:20 +0300] [87425] [INFO] Starting gunicorn 21.2.0
[2024-02-21 18:32:20 +0300] [87425] [INFO] Listening at: http://0.0.0.0:8000 (87425)
[2024-02-21 18:32:20 +0300] [87425] [INFO] Using worker: sync
[2024-02-21 18:32:20 +0300] [87426] [INFO] Booting worker with pid: 87426
[2024-02-21 18:32:20 +0300] [87427] [INFO] Booting worker with pid: 87427
[2024-02-21 18:32:20 +0300] [87428] [INFO] Booting worker with pid: 87428
[2024-02-21 18:32:20 +0300] [87429] [INFO] Booting worker with pid: 87429
[2024-02-21 18:34:51 +0300] [87425] [CRITICAL] WORKER TIMEOUT (pid:87426)
[2024-02-21 18:34:52 +0300] [87425] [ERROR] Worker (pid:87426) was sent SIGKILL! Perhaps out of memory?
[2024-02-21 18:34:52 +0300] [87744] [INFO] Booting worker with pid: 87744
[2024-02-21 18:35:24 +0300] [87425] [CRITICAL] WORKER TIMEOUT (pid:87744)
[2024-02-21 18:35:25 +0300] [87425] [ERROR] Worker (pid:87744) was sent SIGKILL! Perhaps out of memory?
[2024-02-21 18:35:25 +0300] [87820] [INFO] Booting worker with pid: 87820
[2024-02-21 21:56:27 +0300] [7453] [INFO] Starting gunicorn 21.2.0
[2024-02-21 21:56:27 +0300] [7453] [INFO] Listening at: http://0.0.0.0:8000 (7453)
[2024-02-21 21:56:27 +0300] [7453] [INFO] Using worker: sync
[2024-02-21 21:56:27 +0300] [7454] [INFO] Booting worker with pid: 7454
[2024-02-21 21:56:27 +0300] [7455] [INFO] Booting worker with pid: 7455
[2024-02-21 21:56:27 +0300] [7456] [INFO] Booting worker with pid: 7456
[2024-02-21 21:56:27 +0300] [7457] [INFO] Booting worker with pid: 7457
[2024-02-21 22:03:25 +0300] [9205] [INFO] Starting gunicorn 21.2.0
[2024-02-21 22:03:25 +0300] [9205] [INFO] Listening at: http://0.0.0.0:8000 (9205)
[2024-02-21 22:03:25 +0300] [9205] [INFO] Using worker: sync
[2024-02-21 22:03:25 +0300] [9207] [INFO] Booting worker with pid: 9207
[2024-02-21 22:03:25 +0300] [9208] [INFO] Booting worker with pid: 9208
[2024-02-21 22:03:25 +0300] [9209] [INFO] Booting worker with pid: 9209
[2024-02-21 22:03:26 +0300] [9210] [INFO] Booting worker with pid: 9210
>>>>>>> fccd3184b1d7c1d02bacc22ba5cd65083e302b44
